 controller_list:
# It would actually be possible to list both position and effort, moveit will then use what it finds.
# But enforcing a specific one with arg seems more safe to me.
  - name: panda_arm_$(arg control_mode)_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7